pub const DEFAULT_BLOCKLIST: &str = r#"[
        "*://*.pollfish.com/*",
        "*://*.paypalobjects.com/*",
        "*://c.amazon-adsystem.com/*",
        "*://config.aps.amazon-adsystem.com/*",
        "*://securepubads.g.doubleclick.net/*",
        "*://cookiepro.com/*",
        "*://*.cookiepro.com/*",
        "*://cdn.ravenjs.com/*",
        "*://*.poll.fish/*",
        "*://*.paypal.com/*",
        "*://*.twitter.com/*",
        "*://*.youtube.com/*",
        "*://*.doubleclick.net/*",
        "*://unpkg.com/*",
        "*://*.google.com/*",
        "*://*.googletagmanager.com/*",
        "*://apis.google.com/js/platform.js",
        "*://imasdk.googleapis.com/*",
        "*://*.googlesyndication.com/*",
        "*://fran-cdn.frvr.com/*",
        "*://krunker.io/libs/frvr-channel-web*",
        "*://krunker.io/manifest.json*",
        "*://krunker.io/css/google-play.css*",
        "*://krunker.io/libs/zip.js*",
        "*://krunker.io/img/btc_icn.png*",
        "*://krunker.io/img/app_1.png*",
        "*://assets.krunker.io/img/guide/*",
        "*://krunker.io/img/app_0.png.png*",
        "*://krunker.io/img/social/reddit.png*",
        "*://krunker.io/img/social/discord.png*",
        "*://krunker.io/libs/chart.bundle*",
        "*://krunker.io/img/muzflash.png*",
        "*://krunker.io/service-worker.js*",
        "*://krunker.io/libs/fflate*",
        "*://krunker.io/libs/purejscarousel*",
        "*://krunker.io/img/mmok.png*",
        "*://assets.krunker.io/sound/ambient_*",
        "*://assets.krunker.io/models/clouds_0.obj*",
        "*://www.google-analytics.com/*",
        "*://krunker.io/img/client.png*"
    ]"#;

// most are expired, but theyre all in here to cover multiple versions
pub const DEFAULT_FLAGS: [&str; 71] = [
    "--disable-features=msWebOOUI,msPdfOOUI,msSmartScreenProtection",
    // helps with dx hooking
    "--ui-disable-partial-swap",
    "--disable-gpu-sandbox",
    "--enable-unsafe-webgpu",
    "--use-angle=d3d11",
    // rendering
    "--disable-features=TextureLayerSkipWaitForActivation",
    "--disable-gpu-vsync",
    "--disable-vsync-for-tests",
    "--disable-2d-canvas-clip-aa",
    "--disable-composited-antialiasing",
    "--disable-delegated-compositing",
    "--disable-software-rasterizer",
    "--disable-mipmap-generation",
    "--enable-native-gpu-memory-buffers",
    "--force_high_performance_gpu",
    "--ignore-gpu-denylist",
    "--disable-gpu-driver-bug-workarounds",
    "--disable-gpu-watchdog",
    "--enable-features=BlinkCompositorUseDisplayThreadPriority",
    "--enable-features=GpuUseDisplayThreadPriority",
    "--enable-features=BrowserUseDisplayThreadPriority",
    "--enable-accelerated-2d-canvas",
    // computing (?)
    "--disable-features=CalculateNativeWinOcclusion",
    "--disable-background-timer-throttling",
    "--disable-renderer-backgrounding",
    "--disable-best-effort-tasks",
    "--enable-threaded-compositing",
    "--raise-timer-frequency",
    "--wm-window-animations-disabled",
    "--enable-webassembly-threads",
    "--high-dpi-support=1",
    "--disable-low-end-device-mode",
    "--enable-future-v8-vm-features",
    "--enable-features=JavaScriptExperimentalSharedMemory",
    "--enable-features=V8VmFuture",
    "--enable-features=WebAssemblyBaseline,WebAssemblyTiering,WebAssemblyMemory64,WebAssemblyLazyCompilation",
    // network - none of these influence a websocket once it made a connection, maybe loading is a bit faster
    "--enable-quic",
    "--quic-max-packet-length=1460", // 1500 - 40 bytes for headers
    "--no-proxy-server",
    "--no-pings",
    "--dns-over-https=off",
    // telemetry
    "--disable-logging",
    "--disable-metrics-repo",
    "--disable-metrics",
    "--disable-hang-monitor",
    "--disable-breakpad",
    "--disable-crash-reporter",
    "--disable-crashpad-forwarding",
    "--disable-oopr-debug-crash-dump",
    "--disable-in-process-stack-traces",
    "--disable-adpf",
    "--disable-features=HappinessTrackingSurveysForDesktopDemo",
    // disable unimportant in hopes of lowering overhead
    "--disable-bundled-ppapi-flash",
    "--disable-component-update",
    "--disable-nacl",
    "--disable-pnacl-crash-throttling",
    "--disable-print-preview",
    "--disable-threaded-scrolling",
    "--media-router-cast-allow-all-ips=0",
    "--disable-features=slow-dc-timer-interrupts-win",
    "--disable-features=cast-media-route-provider",
    "--disable-features=site-isolation-trial-opt-out",
    "--disable-features=NativeNotifications",
    "--disable-features=webxr-incubations,webxr-runtime",
    "--disable-features=enable-resource-loading-hint",
    "--autoplay-policy=user-gesture-required",
    "--disable-features=MediaRouter",
    "--disable-features=PerformanceInterventionUI",
    "--disable-features=IPH_DemoMode",
    // trackpad gaming??
    "--overscroll-history-navigation=0",
    "--pull-to-refresh=0",
    /*
     0 feasible benefiets
    "--enable-webgl2-compute-context", not used
    "--max-active-webgl-contexts=100", krunker does NOT use 100 webgl contexts
    "--renderer-process-limit=100",  krunker does NOT use 100 renderer processes
    "--in-process-gpu", worse than disable-gpu-sandbox
    "--enable-javascript-harmony", krunker doesnt use experimental features
    "--webrtc-max-cpu-consumption-percentage=100",
    "--max-gum-fps=9999", related to gameusermedia, some guy deadass saw fps in the name and everyone went with it
    "--disable-features=reduced-referrer-granularity", counter productive
    */
];
